### ISSUE TITLE
生成向量用的是text-embedding-ada-002

### ISSUE THREAD

**Issue by asfman** [SkywalkerDarren/chatWeb#4]
ai.py 里embedding = openai.Embedding.create(model="text-embedding-ada-002", inpu
    t=text)， 但是你首页说明里说生成向量用的是gpt-3.5-turbo

**Comment by SkywalkerDarren** [comment]
gpt-3.5-turbo不支持向量生成 https://platform.openai.com/docs/guides/embeddings/embedding-models

**Comment by SkywalkerDarren** [comment]
https://openai.com/blog/new-and-improved-embedding-model
